"""Build lesson pages from their sources.

Each lesson folder has a `lesson.html` source that starts with a small
header block and then the page body:

    title: Gradient Descent by Hand
    description: …
    slug: gradient-descent
    ---
    <header class="lesson-hero">…

This script wraps it with the shared <head>, nav, scripts and footer and
writes `<folder>/index.html`, so every lesson shares one design.

    python lesson/build.py            # build every lesson
    python lesson/build.py cnn ols    # build some
"""
import html
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = "https://deepdivefromscratch.zichaoleng55.workers.dev"
VERSION = "11"  # bump to bust caches after changing shared assets


def partials():
    idx = (ROOT / "index.html").read_text(encoding="utf-8")
    logo = re.search(r'<span class="nav-brand-icon">(.*?)</span>', idx, re.S).group(1)
    fav = re.search(r'<link rel="icon" href="([^"]+)"', idx).group(1)
    theme = re.search(r'(<button class="theme-toggle".*?</button>)', idx, re.S).group(1)
    return logo, fav, theme


def build(folder: pathlib.Path):
    src = (folder / "lesson.html").read_text(encoding="utf-8")
    head, body = src.split("\n---\n", 1)
    meta = dict(line.split(":", 1) for line in head.strip().splitlines())
    meta = {k.strip(): v.strip() for k, v in meta.items()}
    logo, fav, theme = partials()
    slug, title, desc = meta["slug"], meta["title"], meta["description"]
    extra_js = "".join(f'\n<script src="{s.strip()}?v={VERSION}"></script>' for s in meta.get("scripts", "").split(",") if s.strip())
    mathjax = """
  <script>
    window.MathJax = {
      tex: { inlineMath: [['\\\\(','\\\\)']], displayMath: [['\\\\[','\\\\]']], packages: { '[+]': ['ams'] } },
      options: { skipHtmlTags: ['script','noscript','style','textarea'] }
    };
  </script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" id="MathJax-script" async></script>""" if meta.get("math", "yes") != "no" else ""
    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{html.escape(title)} | Deep Dive From Scratch</title>
  <meta name="description" content="{html.escape(desc)}" />
  <link rel="canonical" href="{SITE}/{slug}/" />
  <script type="application/ld+json">
  {{ "@context": "https://schema.org", "@type": "Article", "headline": {json_str(title)}, "description": {json_str(desc)}, "url": "{SITE}/{slug}/", "author": {{ "@type": "Person", "name": "Deep Dive From Scratch" }} }}
  </script>
  <link rel="icon" href="{fav}" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet" />
  <script src="../theme.js?v={VERSION}"></script>
  <link rel="stylesheet" href="../style.css?v={VERSION}" />
  <link rel="stylesheet" href="../home.css?v={VERSION}" />
  <link rel="stylesheet" href="../lesson/lesson.css?v={VERSION}" />{mathjax}
</head>
<body class="home lesson" data-lesson="{slug}">

<!-- Generated by lesson/build.py from lesson.html — edit the source, not this file. -->
<nav class="top-nav">
  <a href="/" class="nav-brand">
    <span class="nav-brand-icon">{logo}</span>
    <span class="nav-brand-text">Deep Dive From Scratch</span>
  </a>
  <div class="nav-right">
    <div class="nav-links">
      <a href="/#posts" class="hide-sm">Lessons</a>
      <a href="/about.html" class="hide-sm">About</a>
      <a href="https://buymeacoffee.com/zichao98" target="_blank" rel="noopener" class="nav-bmc" aria-label="Buy me a coffee">☕<span class="bmc-text"> Buy me a coffee</span></a>
    </div>
    {theme}
  </div>
</nav>
{body.strip()}

<footer class="footer-x">
  <p>© 2026 Deep Dive From Scratch · Built with plain HTML, math, and curiosity · <a href="https://github.com/zichao98" target="_blank" rel="noopener">GitHub</a></p>
</footer>
<script src="../lesson/lesson.js?v={VERSION}"></script>{extra_js}
</body>
</html>
"""
    (folder / "index.html").write_text(page, encoding="utf-8", newline="\n")
    print("built", folder.name)


def json_str(s):
    import json
    return json.dumps(s, ensure_ascii=False)


if __name__ == "__main__":
    names = sys.argv[1:] or [p.parent.name for p in ROOT.glob("*/lesson.html")]
    for name in names:
        build(ROOT / name)
